name: Run Cypress BDD Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_valid_usn: ${{ secrets.CYPRESS_valid_usn }}
          CYPRESS_valid_pass: ${{ secrets.CYPRESS_valid_pass }}

      - name: Upload screenshots if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
